import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.9.1/firebase-app.js';
import {getFirestore,doc,getDoc,collection,query,where,orderBy,onSnapshot,addDoc,deleteDoc,serverTimestamp,Timestamp} from 'https://www.gstatic.com/firebasejs/11.9.1/firebase-firestore.js';
import {firebaseConfig,appConfig} from './firebase-config.js';

const $=id=>document.getElementById(id), START=480,END=1140,SLOT=30,ROW=48;
let store,room,viewMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDate,bookings=[],activeBooking,unsubscribe;
const ready=()=>firebaseConfig.apiKey&&!firebaseConfig.apiKey.startsWith('YOUR_')&&firebaseConfig.projectId&&!firebaseConfig.projectId.startsWith('YOUR_');
const k=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const same=(a,b)=>k(a)===k(b),tm=m=>`${Math.floor(m/60)%12||12}:${String(m%60).padStart(2,'0')} ${m>=720?'PM':'AM'}`;
const at=(d,m)=>new Date(d.getFullYear(),d.getMonth(),d.getDate(),Math.floor(m/60),m%60),mins=ts=>{const d=ts.toDate();return d.getHours()*60+d.getMinutes()};
function show(id){$(id).classList.add('show');setTimeout(()=>$(`${id}`).querySelector('button,input,select')?.focus(),0)}function hide(id){$(id).classList.remove('show')}
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}
function busy(b,on,text){b.disabled=on;b.dataset.text??=b.textContent;b.textContent=on?text:b.dataset.text}
function clock(){const d=new Date();$('clock').textContent=d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});$('todayLabel').textContent=d.toLocaleDateString('en-MY',{weekday:'short',day:'numeric',month:'short'})}
function setup(){clock();setInterval(clock,15000);$('prevMonth').onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()-1,1);listen()};$('nextMonth').onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,1);listen()};$('todayBtn').onclick=()=>{viewMonth=new Date();viewMonth.setDate(1);listen()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>hide(x.dataset.close));document.querySelectorAll('.overlay').forEach(x=>x.onclick=e=>{if(e.target===x&&x.id!=='setupOverlay')hide(x.id)});document.onkeydown=e=>{if(e.key==='Escape')document.querySelectorAll('.overlay.show:not(#setupOverlay)').forEach(x=>hide(x.id))};$('backToSchedule').onclick=()=>{hide('bookingOverlay');show('dayOverlay')};$('backFromDetail').onclick=()=>{hide('detailOverlay');show('dayOverlay')};$('bookingForm').onsubmit=book;$('cancelBooking').onclick=cancel}
async function init(){setup();if(!ready()){show('setupOverlay');return}const app=initializeApp(firebaseConfig);store=getFirestore(app);await loadRoom();listen()}
async function loadRoom(){const snap=await getDoc(doc(store,'rooms',appConfig.roomId));if(!snap.exists()){toast('Room setup is missing. Add the room document in Firestore.');return}room={id:snap.id,...snap.data()};$('roomName').textContent=room.name;$('roomMeta').textContent=`${room.department||'Meeting Room'} · Capacity ${room.capacity} · ${room.location||'Location —'}`;$('attendees').max=room.capacity}
function listen(){if(!room)return;unsubscribe?.();const start=k(viewMonth),end=k(new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,0));const q=query(collection(store,'bookings'),where('roomId','==',room.id),where('status','==','confirmed'),where('dayKey','>=',start),where('dayKey','<=',end),orderBy('dayKey'),orderBy('startAt'));unsubscribe=onSnapshot(q,s=>{bookings=s.docs.map(d=>({id:d.id,...d.data()}));renderMonth();status();if(selectedDate&&$('dayOverlay').classList.contains('show'))timeline()},e=>toast('Could not load bookings: '+e.message))}
function renderMonth(){$('monthCurrent').textContent=viewMonth.toLocaleDateString('en-MY',{month:'long',year:'numeric'});const grid=$('monthGrid');grid.innerHTML='';const now=new Date(),offset=viewMonth.getDay(),days=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,0).getDate();for(let i=0;i<offset;i++){const x=document.createElement('span');x.className='day-cell empty';grid.append(x)}for(let n=1;n<=days;n++){const d=new Date(viewMonth.getFullYear(),viewMonth.getMonth(),n),items=bookings.filter(b=>same(b.startAt.toDate(),d)),past=d<new Date(now.getFullYear(),now.getMonth(),now.getDate()),b=document.createElement('button');b.type='button';b.className='day-cell'+(same(d,now)?' today':'');b.disabled=past;b.setAttribute('aria-label',`${d.toLocaleDateString('en-MY',{day:'numeric',month:'long'})}, ${items.length} bookings`);b.onclick=()=>day(d);const num=document.createElement('span');num.className='day-num';num.textContent=n;b.append(num);items.slice(0,2).forEach(v=>{const c=document.createElement('span');c.className='day-chip';c.textContent=`${v.startAt.toDate().toLocaleTimeString('en-MY',{hour:'numeric',minute:'2-digit'})} ${v.purpose}`;b.append(c)});if(items.length>2){const m=document.createElement('span');m.className='day-more';m.textContent=`+${items.length-2} more`;b.append(m)}grid.append(b)}}
function dayItems(){return bookings.filter(b=>selectedDate&&same(b.startAt.toDate(),selectedDate))}function day(d){selectedDate=new Date(d);$('dayTitle').textContent=d.toLocaleDateString('en-MY',{weekday:'long',day:'numeric',month:'long'});timeline();show('dayOverlay')}
function timeline(){const box=$('timeline'),items=dayItems(),now=new Date();box.innerHTML='';for(let m=START;m<END;m+=SLOT){const r=document.createElement('div');r.className='slot-row';const l=document.createElement('span');l.className='slot-time';l.textContent=tm(m);const b=document.createElement('button');b.type='button';b.className='slot-button';const taken=items.some(x=>m<mins(x.endAt)&&m+SLOT>mins(x.startAt));b.disabled=taken||at(selectedDate,m)<=now;b.textContent=b.disabled?'':'+ Book';b.onclick=()=>form(m);r.append(l,b);box.append(r)}items.forEach(x=>{const st=mins(x.startAt),en=mins(x.endAt),b=document.createElement('button');b.type='button';b.className='event-block';b.style.top=`${(st-START)/SLOT*ROW+2}px`;b.style.height=`${Math.max((en-st)/SLOT*ROW-4,28)}px`;b.innerHTML=`<div class="event-title"></div><div class="event-meta"></div>`;b.firstChild.textContent=x.purpose;b.lastChild.textContent=`${tm(st)}–${tm(en)} · ${x.attendees} attendee${x.attendees===1?'':'s'}`;b.onclick=()=>detail(x);box.append(b)});if(same(now,selectedDate)){const m=now.getHours()*60+now.getMinutes();if(m>=START&&m<=END){const l=document.createElement('div');l.className='now-line';l.style.top=`${(m-START)/SLOT*ROW}px`;box.append(l)}}}
function form(start){hide('dayOverlay');$('bookingForm').reset();$('attendees').value=4;$('attendees').max=room.capacity;$('bookingDate').textContent=selectedDate.toLocaleDateString('en-MY',{weekday:'long',day:'numeric',month:'long'});$('bookingError').textContent='';const s=$('startTime'),e=$('endTime');s.innerHTML='';for(let m=START;m<END;m+=SLOT)s.add(new Option(tm(m),m));s.value=start;const update=()=>{e.innerHTML='';const from=+s.value,next=dayItems().map(x=>mins(x.startAt)).filter(x=>x>from).sort((a,b)=>a-b)[0]||END;for(let m=from+SLOT;m<=Math.min(next,END);m+=SLOT)e.add(new Option(tm(m),m));e.value=Math.min(from+60,+e.options[e.options.length-1].value)};s.onchange=update;update();show('bookingOverlay')}
async function book(e){e.preventDefault();const b=$('submitBooking'),st=+$('startTime').value,en=+$('endTime').value,attendees=+$('attendees').value;busy(b,true,'Booking…');$('bookingError').textContent='';try{if(!Number.isInteger(attendees)||attendees<1||attendees>room.capacity)throw new Error(`Enter 1 to ${room.capacity} attendees.`);if(dayItems().some(x=>st<mins(x.endAt)&&en>mins(x.startAt)))throw new Error('That time has just been booked. Please choose another slot.');const startAt=at(selectedDate,st),endAt=at(selectedDate,en);const result=await addDoc(collection(store,'bookings'),{roomId:room.id,status:'confirmed',dayKey:k(selectedDate),purpose:$('purpose').value.trim(),attendees,startAt:Timestamp.fromDate(startAt),endAt:Timestamp.fromDate(endAt),createdAt:serverTimestamp()});hide('bookingOverlay');toast(`Booking confirmed: ${result.id}`);show('dayOverlay')}catch(err){$('bookingError').textContent=err.message||'Booking failed.'}finally{busy(b,false)}}
function detail(x){activeBooking=x;hide('dayOverlay');const rows=[['Purpose',x.purpose],['Time',`${tm(mins(x.startAt))} – ${tm(mins(x.endAt))}`],['Attendees',x.attendees]];$('bookingDetails').innerHTML='';rows.forEach(([a,v])=>{const r=document.createElement('div');r.className='detail-row';r.innerHTML='<span></span><span></span>';r.firstChild.textContent=a;r.lastChild.textContent=v;$('bookingDetails').append(r)});$('cancelBooking').classList.remove('hidden');show('detailOverlay')}
async function cancel(){if(!activeBooking||!confirm('Delete this booking? This cannot be undone.'))return;const b=$('cancelBooking');busy(b,true,'Deleting…');try{await deleteDoc(doc(store,'bookings',activeBooking.id));hide('detailOverlay');toast('Booking deleted.');show('dayOverlay')}catch(e){toast(e.message)}finally{busy(b,false)}}
function status(){const now=new Date(),items=bookings.filter(b=>same(b.startAt.toDate(),now)),cur=items.find(b=>now>=b.startAt.toDate()&&now<b.endAt.toDate()),next=items.find(b=>b.startAt.toDate()>now),p=$('statusPill');p.className='status-pill '+(cur?'busy':'free');$('statusText').textContent=cur?'IN USE':'AVAILABLE';$('statusNote').textContent=cur?`${cur.purpose} · until ${cur.endAt.toDate().toLocaleTimeString('en-MY',{hour:'numeric',minute:'2-digit'})}`:next?`Available until ${next.startAt.toDate().toLocaleTimeString('en-MY',{hour:'numeric',minute:'2-digit'})}`:'Available for the rest of today'}
init().catch(e=>{console.error(e);toast('Application startup failed: '+e.message)});
